### ISSUE TITLE
Is therer anyway to include mathjax since there is no layout folder in minima?

### ISSUE THREAD

**Issue by youngji-cho** [jekyll/minima#100]
I have learn that to add mathjax, I have to include mathjax scrpit in " layouts" folder. "http://stackoverflow.com/questions/10987992/using-mathjax-with-jekyll"

In minima version, there is no "layout"folder. 
http://stackoverflow.com/questions/38891463/jekyll-default-installation-doesnt-have-layouts-directory

Is there any way to include mathjax in minima?

**Comment by DirtyF** [comment]
By default you don't see `_layouts`, `_includes` folders because the theme uses the ones stored in the gem. In order to customize a theme, you'll need to [override theme's files](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) or add new ones.

To know that, you must able to study the theme's files, for minima an easy way is to look at the code on this repository.

I don't know MathJax, but I would:

- store JS scripts in assets/js/ or [use Mathjax CDN](http://docs.mathjax.org/en/latest/start.html)
- create an include to insert the script tag in `_includes/mathjax.html`
- copy and edit [_layouts/post.html](https://github.com/jekyll/minima/blob/master/_layouts/post.html) and insert something like

```liquid
{% if page.math != false %}
 {% include mathjax.html %}
{% endif %}
```

So that everytime you need to use Mathjax in a post, you add this in the post Front Matter:

```yaml
math: true
```
