### ISSUE TITLE
How to update theme?

### ISSUE THREAD

**Issue by gatezh** [jekyll/minima#123]
There's a lot of fixes had been merged recently (like this one #111) and I would like to have those changes in my project.
Couldn't find a way to update my theme to the latest version.
According to [Jekyll documentation](https://jekyllrb.com/docs/themes/) it was supposed to be done with `bundle update minima` command, but nothing is happening.

Can anybody explain how it works, please?

**Comment by DirtyF** [comment]
Hi, we haven't release a new Gem with this modification yet so bundle update won't help here.

If you really want to update before the new gem is released, you can update your _config.yml like this:

```yaml
gem "minima", :github => "jekyll/minma", :branch => "master"
```

**Comment by ashmaroli** [comment]
@DirtyF A typo in your comment above. It should be `Gemfile` instead of `_config.yml`
Also, `:github` uses the `http://`protocol that'll throw a warning. Instead, recommend using `:git` with `https;//`:
```
:git => "https://github.com/jekyll/minima.git", :branch =>
```

**Comment by gatezh** [comment]
Maybe it makes sense to create some Wiki of FAQ for questions like this?
Or it was too obvious? :)

**Comment by DirtyF** [comment]
@gatezh Nothing is ever obvious, but as we rely on bundler for handling gems, users can safely rely on [bundler's documentation](https://bundler.io/v1.14/git.html) when it comes to update gem-based theme. 

This is an edge-case mostly useful for testing a feature of your your theme locally, normally you shouldn't have to do this in order to use a theme.

If you feel like this should be mentioned in the README, you're welcome to submit a PR ✍️
