### ISSUE TITLE
Only show a certain number of posts per page.

### ISSUE THREAD

**Issue by jaredsburrows** [jekyll/minima#159]
It seems like the index/home will continue to show all posts. What happens when a user hits 100? 1000? Even as static HTML, it is a lot to load, especially for mobile. 

Can we limit each page to like 50 or 100? Could we make it configurable?

**Comment by DirtyF** [comment]
Hi @jaredsburrows 

There's an open PR about this: https://github.com/jekyll/minima/pull/150

If you have a lot of posts, you should be able to add [pagination](https://jekyllrb.com/docs/pagination/) and [override](https://jekyllrb.com/docs/themes/#overriding-theme-defaults) the `index.html` file of the theme.

If you need pagination on categories or collections, I suggest you take a look on https://github.com/sverrirs/jekyll-paginate-v2 (but it's not supported by GitHub Pages)

**Comment by jaredsburrows** [comment]
@DirtyF Hey, do you have an example project that _does_ work with Github pages? Thanks for the reply by the way.

**Comment by DirtyF** [comment]
@jaredsburrows Posts pagination is supported by default on GitHub Pages, you just have to specify some parameters in your `_config.yml`:

```yaml
paginate: 1
paginate_path: "/page/:num/"
```

Then you loop over `paginator.posts` instead of `site.posts` as mentioned in the docs.
Make sure you pagination URLs are properly built, e.g. I had to add `relative_url` filter to next and previous links.

Here's a basic example with default GitHub Pages theme (primer), it works also for `minima`: 
[Pagination demo repository](https://github.com/DirtyF/github-pages-test) - [Pagination basic demo](https://dirtyf.github.io/github-pages-test/)

**Comment by begueradj** [comment]
Without pagination, the default theme is useless when you have lot of posts.

**Comment by claudiuconstantin** [comment]
Whats's the status here? Pagination would be nice for this default theme

**Comment by begueradj** [comment]
Still the same

**Comment by prashanthmadi** [comment]
Thanks for all great work.. Looking forward for this feature

**Comment by prashanthmadi** [comment]
I was able to make it work following pull request of @DirtyF . Thanks for help.
https://github.com/prashanthmadi/prashanthmadi.github.io
