### ISSUE TITLE
Theme hardcodes CSS path to `css/main.css`

### ISSUE THREAD

**Issue by benbalter** [jekyll/minima#16]
That means that if I'm adding minima to a site, I have to create an entire CSS folder, even if I only have one CSS file. 

Instead, it should be `assets/style.scss`(or similar) where the downstream users may have a use for storing other assets in that folder.

**Comment by benbalter** [comment]
Is there any way to implement this without breaking existing sites?

**Comment by davidyell** [comment]
I found this because I was constantly getting an error with a missing css file because it Jekyll was looking in `assets/main.css` instead of `css/main.css`. I've had to overload the theme in my local project to solve this.

If this is the default, then everyone who uses Jekyll for the first time will always get a site without any css.

**Comment by ashmaroli** [comment]
This issue has been resolved, is it not?

**Comment by ashawley** [comment]
Yeah, seems this was fixed in #43 and released in 2.0?
