### ISSUE TITLE
Social media list is hidden

### ISSUE THREAD

**Issue by alhaad** [jekyll/minima#181]
See https://jekyll.github.io/minima/

**Comment by DirtyF** [comment]
fixed.

**Comment by michaelnordmeyer** [comment]
How. In which commit?

My list is still hidden.

**Comment by DirtyF** [comment]
@michaelnordmeyer I think it was in https://github.com/jekyll/minima/commit/d3b57ca46bd69c29342ca9696eb1c317d3c5dde6

**Comment by michaelnordmeyer** [comment]
Hm, then we're talking about different problems.

My social media list is rendered in HTML (so no disappearing icons because of wrong `site.xxx_username`), but for whatever reason some elements are hidden:

```html
<ul class="social-media-list" frt2evt="" hidden="">
  <li>
    <a href="https://github.com/xxx" rel="me">
      <svg class="svg-icon">
        <use xlink:href="/assets/minima-social-icons.svg#github"></use>
      </svg> <span class="username">xxx</span>
    </a>
  </li>
  <li>
    <a href="https://www.linkedin.com/in/xxx" rel="me">
      <svg class="svg-icon">
        <use xlink:href="/assets/minima-social-icons.svg#linkedin"></use>
      </svg> <span class="username">xxx</span>
    </a>
  </li>
  <li>
    <a href="https://www.twitter.com/xxx" rel="me">
      <svg class="svg-icon">
        <use xlink:href="/assets/minima-social-icons.svg#twitter"></use>
      </svg> <span class="username">xxx</span>
    </a>
  </li>
</ul>
```

```css
:root .social-media-list, :root .icon--linkedin, :root .icon--twitter {
    display: none !important;
}
```

None of those are in the source HTML and CSS.

It was working until yesterday when I upgraded from minima 2.1.1 to 2.3.0. I checked all my commits and the commits of minima after 2.1.1 to no avail. I use Github Pages.

Any idea?

**Comment by michaelnordmeyer** [comment]
Nevermind, I found the problem. µBlock Origin was blocking the list:

> Static filter `-social-icons.` found in:
> Fanboy’s Annoyance List
> Fanboy’s Social Blocking List
