### ISSUE TITLE
How to remove the subscribe via RSS from home

### ISSUE THREAD

**Issue by pr0PM** [jekyll/minima#375]
I recently made a static website using minima as theme in jekyll but I am unable to find a solution to remove the "subscribe via RSS " text from my home.
I successfully did it on my local machine by removing the feed.xml under the _sites and editing the file in _layouts in the minima but after commit and publishing on my github repository its again reverted to its previous state also no online documentation is available in this issue.

**Comment by DirtyF** [comment]
[Override](https://jekyllrb.com/docs/themes/#overriding-theme-defaults)  the home layout and remove the link in 
https://github.com/jekyll/minima/blob/d0cedd9080ecc4d33aaa573620a4d8658c5ccca8/_layouts/home.html#L31

**Comment by pr0PM** [comment]
I already said that I have done this it works on my local machine but not in the live website on github pages.

**Comment by ashmaroli** [comment]
@pr0PM Three things to keep in miind while developing a Jekyll site:
1. Contents of `_site` are changed on every build.
2. Making changes to your local installation of gem does mean that those changes get reflected on GitHub Pages.
3. The correct way to override a theme in jekyll is to do the following:
  - Make a copy of the template in your source directory. i.e., since you want to override the `home` layout, ensure that you have a `_layouts/home.html` at the root of your source directory.
  - If you're making a change to an "include", then have a copy of the include at source as well..

**Comment by pr0PM** [comment]
Ok thanks I was looking for this it works now. Thanks again for the quick clarification.

**Comment by amaarora** [comment]
>    * If you're making a change to an "include", then have a copy of the include at source as well..

Thank you very much! This worked.
