### ISSUE TITLE
Missing the minima files in my Jekyll folders.

### ISSUE THREAD

**Issue by gruberb** [jekyll/minima#38]
I created a new Jekyll "project", and the default theme is minima. But I cannot see any minima specific files (like footer, header etc.). How can I adjust the footer, header and general structure in this theme? Can I somehow get all the necessary files and build it my own?

**Comment by DirtyF** [comment]
@gruberb You have to copy the files you want to override in your website folder. By default they're stored in the gems folders. To locate the theme's files on your computer, you can use `bundle show minima` and then `cp` the desired files.

See: https://jekyllrb.com/docs/themes/#overriding-theme-defaults
If it's not detailed enough, please open a PR to help us improve the docs, I'll be happy to review it.

**Comment by gruberb** [comment]
Thanks a lot! This solved my problem! I will create a PR try to explain it a bit better for newbies like me :)

**Comment by DirtyF** [comment]
@gruberb The overall idea of Jekyll gem-based-themes is to abstract complexity for the users and remove the need to clone repository. After a few weeks, we are learning that hiding all files by default seems unintuitive when it comes to do small changes. 

In order to provide more configuration options, I'll be interested in knowing what kind of changes you need to do on jekyll's default theme. The idea is to provide more customization options, without having to deal with the theme's files. Thanks.

**Comment by kreck** [comment]
@DirtyF i struggled finding the minima files, too. A little hint in the README would be nice. To give an example of the changes i need to make:
- Adjust header - color
- Add Logo/Image to Header
- Adjust link colors

Best regards

**Comment by DirtyF** [comment]
@kreck thanks for the feedback so basically variables stored in `_config.yml` or in a Sass file should do the trick. But these files should be visible to users by default, or at least instructions should be given in the README for customization.
