### ISSUE TITLE
How Can I get v3.0?

### ISSUE THREAD

**Issue by AleSpreafico** [jekyll/minima#419]
Hello
Reading the docs I saw minima 3.0 new features... but I cannot get it from my Gemfile

Is it not released yet?

**Comment by ashmaroli** [comment]
Minima v3.0 has not been released yet..

**Comment by DirtyF** [comment]
Feel free to [get your gem from the repository](https://bundler.io/v1.12/git.html):

`gem "minima", github: "jekyll/minima"`

**Comment by travisdowns** [comment]
> Feel free to [get your gem from the repository](https://bundler.io/v1.12/git.html):
> 
> `gem "minima", github: "jekyll/minima"`

Do you know if that method works also with github pages? I.e., does github whitelist that source?

**Comment by ashmaroli** [comment]
@travisdowns GitHub Pages doesn't allow using *custom* versions of any gem. The easiest way to use with GitHub Pages is to simply fork the repository and add your customization.

If your source is already a fork of Minima, you could use `git pull` to fetch the repo's current state. This could be a bit challenging because there'll be merge-conflicts proportional to the customization you've already made.

**Comment by ashmaroli** [comment]
@travisdowns and @AleSpreafico It just dawned on me that you can use the current state of `master` via the `remote_theme` feature in GitHub Pages:
```yaml
remote_theme: jekyll/minima
```

**Comment by derek-adair** [comment]
...will this ever be released? :)
