### ISSUE TITLE
2.5.1 can't include custom-head.html

### ISSUE THREAD

**Issue by junhan-z** [jekyll/minima#472]
I tried 
```
gem "minima", github: "jekyll/minima"
```
use `bundle install` it will installs `2.5.0` and it includes my head from _includes/custom-head.html

However, if I change to 
```
gem "minima", "~> 2.5"
```
`bundle install` will install `2.5.1`, which breaks the include.

**Comment by junhan-z** [comment]
Yep, as I checked the gem I have under:
`.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/minima-2.5.1`

```
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {%- seo -%}
  <link rel="stylesheet" href="{{ "/assets/main.css" | relative_url }}">
  {%- feed_meta -%}
  {%- if jekyll.environment == 'production' and site.google_analytics -%}
    {%- include google-analytics.html -%}
  {%- endif -%}
</head>
```

The include custom-head part is missing... Interesting as current master actually has it, was there a rollback? I don't know much about gem release though.

**Comment by hszhakka** [comment]
The `custom-head.html` was added to the `master` branch but that is not yet to release, so in the  2.5.1 version, Minima doesn't have this file.

If you want to taste the latest Minima, I recommend you use [`jekyll-remote-theme`](https://github.com/benbalter/jekyll-remote-theme) to refer to the `master` branch of Minima.

**Comment by junhan-z** [comment]
Thanks @hszhakka. So my understanding is once it is released, 2.5.1 will have it? Curious what is controlling what to release and why it was not released?

 So far I used `gem "minima", github: "jekyll/minima"` which gives me 2.5.0 and it works fine for me, for now.

**Comment by hszhakka** [comment]
The next time to release, the version should be 3.0, I guess. So you can use `custom-head.html` in Minima 3.0, but not in 2.5.1. When a gem was release, it won't be modified again.

`gem "minima", github: "jekyll/minima"` tells Ruby to fetch the gem Minima from a *GitHub* repository, i.e. from https://github.com/jekyll/minima.git. It would download the `master` branch, that's why you can use `custom-head.html` in this case. But why the version is 2.5.0? Because the version specified in the [`gemspec`](https://github.com/jekyll/minima/blob/master/minima.gemspec) file remains in 2.5.0, that makes you think you are using 2.5.0, but in fact, you are using the `master` branch.

**Comment by FernandoBasso** [comment]
I spent some time trying to figure out why it was not working when I was doing precisely what was written in the README about `custom-head.html`. So, the master branch is _not_ minima 2.5.1?

**Comment by RESISTORS** [comment]
I rolled back to 2.5.0 and it had the same problem; the custom-head.html was not included.

I finally just copied _includes/head.html from the gem into my project. I was glad I did because it also used a different css location from the 2.5.1 that is on the github website! I added the include back in and it works.

I never asked for anything but a production build, so it seems very strange to me that the 2.5.1 gem is quite different from the 2.5.1 on github. I have never seen this happen anywhere else.

Glad I found this thread, thanks!

**Comment by natkuhn** [comment]
I rolled back to 2.5.0 and it had the same problem; the custom-head.html was not included.

I finally just copied _includes/head.html from the gem into my project. I was glad I did because it also used a different css location from the 2.5.1 that is on the github website! I added the include back in and it works.

I never asked for anything but a production build, so it seems very strange to me that the 2.5.1 gem is quite different from the 2.5.1 on github. I have never seen this happen anywhere else.

Glad I found this thread, thanks!

**Comment by junhan-z** [comment]
Another problem is if use the 2.5.1, you won't be able to override the variables via using custom-variable.sass.

So I guess the only solution now is stick to master to utilize the latest changes before 3.0 is released.

**Comment by cschep** [comment]
When I switch to using master to get the custom-head, I end up with this error: `Jekyll::Converters::Scss::SyntaxError: Error: File to import not found or unreadable: minima.`

Anyone see this?

**Comment by ngzhio** [comment]
> When I switch to using master to get the custom-head, I end up with this error: `Jekyll::Converters::Scss::SyntaxError: Error: File to import not found or unreadable: minima.`
> 
> Anyone see this?

Is there any file named "minima" in your repository? It seems that the file can't be found.

**Comment by cschep** [comment]
For anyone else that hits this problem, in the old version you could `@import minima` but in the new version you have to pick a theme and initialize.

```
@import
  "minima/skins/{{ site.minima.skin | default: 'classic' }}",
  "minima/initialize";
```

I think we're in kind of a weird transition state here.
