### ISSUE TITLE
Skins does not work

### ISSUE THREAD

**Issue by anthavio** [jekyll/minima#543]
Maybe I do not understand instructions but simple workflow does not work

> jekyll new blog 
> cd blog
> bundle exec jekyll serve

Site with classic skin is displayed

Now edit _config.yml and add

```
minima:
  skin: dark
```

> bundle exec jekyll serve

Nothing changes and classic skin is displayed. Do I need to add my own assets/css/style.scss to make it work ?

minima-2.5.1
jekyll-4.1.1

**Comment by ashmaroli** [comment]
Skins are part of new unreleased features of this theme. Since it is unreleased, you won't be able to use it via `jekyll new` automatically.
In order to use the feature, you should do *either of the following*:
- Edit your Gemfile to use the repository version of the `minima` theme.
- Use the `jekyll-remote-theme` plugin to pull in the theme contents.
- Fork this repository and build it directly after adding your content files.

**Comment by anthavio** [comment]
Thank you! I'm ruby noob so I'll wait until official minima version is released. Are there any plans for release?
