### ISSUE TITLE
To hide footer social_links twitter icon need manual comment into _includes/social.html  

### ISSUE THREAD

**Issue by alemens** [jekyll/minima#593]
### Description 
Even though no twitter declared into `_config.yml`, the footer `social_links` twitter icon still rendered. 
So to hide it need a manual comment into `_includes/social.html`

### Expected behavior
If no `social_links` twitter declared into `_config.yml` I am aspecting this will not be rendered.

###### Create new site
```bash
jekyll new testingbug
```

###### Modify /testingbug/Gemfile to use the GitHub version
```yaml
#gem "minima", "~> 2.5"
gem "minima", git: "https://github.com/jekyll/minima"
```

###### Edit _config.yml
```yaml
minima:
  social_links:
    github:  testingbug
```

###### Build and update with bundle 
```bash
bundle install && bundle update
```

**Comment by dflorance** [comment]
The issue is still there.  

If I put in my _config.yml : 
- "twitter:" (no value) it will link to jekyllrb account
- "twitter: ''"  (empty value) it will link to home of twitter
- no twitter value it will link to jekyllrb account

It comes from the theme _config.yml which contain a default value for twitter that could be unset. By the way the same thing happens with all values like social_links.github, author.email and author.name . The easiest way would be to just comment these default values in the theme _config.yml .

Like 

```bash
  title: Your awesome title
  author:
    # name: GitHub User
    # email: your-email@domain.com
  ...
    # generate social links in footer
    social_links:
      # twitter: jekyllrb
      # github:  jekyll
      # devto: jekyll
      # dribbble: jekyll
      # facebook: jekyll
```

Hope my comment will help.

**Comment by ashmaroli** [comment]
@alemens, @dflorance You'll have to instruct Jekyll to *ignore* the theme-config explicitly:
```yml
# in <source_dir>/_config.yml

ignore_theme_config: true
```

**Comment by dflorance** [comment]
@ashmaroli you are perfectly right ! My bad for not knowing about this option, from my perspective I think the issue can be close or stale as this option exists.
