### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by orschiro** [jekyll/minima#67]
Thank you so much for this great theme!

How about a demo for the always latest version of the theme?

**Comment by DirtyF** [comment]
@jekyll/minima cold we push `example/_site` to `gh-branch` with a rake task?

**Comment by benbalter** [comment]
> cold we push example/_site to gh-branch with a rake task?

Jekyll themes are intended to be Jekyll sites (for exactly this purpose... so that the repo itself can serve as the demo). Content file are excluded by the Gemspec and not distributed with the theme.

I turned on Pages for `master` of this repo... if someone submits a PR to move the contents of https://github.com/jekyll/minima/tree/master/example to root, it should Just Work (TM).

**Comment by ashmaroli** [comment]
> I turned on Pages for master of this repo... if someone submits a PR to move the contents of https://github.com/jekyll/minima/tree/master/example to root, it should Just Work (TM).

IMHO, it would be *better* if we renamed the `/example/` to `/docs/`:
  - pros:
    - GitHub automatically generates a new site with every merge to `master`
    - the folder remains a viable example to showcase how exactly a site using **theme gems** would be by default.
    - the *Development* section in README wouldn't change. 

  - cons:
    - unsemantic name for a demo directory. ( can be solved by using a rake task to manually publish instead, similar to `jekyllrb.com`

**Comment by benbalter** [comment]
@ashmaroli the issue is, that the layouts, includes, assets, etc. are all in the root directly. If we move to the `/docs` folder, we'll have to symlink those directories, build maually, etc. Themes are intended to be valid Jekyll sites.
