### ISSUE TITLE
Adding custom CSS styles

### ISSUE THREAD

**Issue by alexsmacd** [jekyll/minima#810]
I am using GitHub pages with the Minima theme for a small project.

I would like to add some additional, custom CSS styles, but I am having a heck of a time. To clarify, these are not overrides, because they are completely separate from the existing styles.

I tried following the directions [here](https://github.com/jekyll/minima/tree/master?tab=readme-ov-file#customizing-templates), and also tried adding a custom-head.html file that linked to an additional stylesheet.

Neither one worked. What am I missing?

**Comment by ashmaroli** [comment]
Hello @alexsmacd
I am sorry that you are facing difficulties customizing Minima.

But I cannot help you **much** since you have not given me any details about your situation.
However, with the breadcrumbs you've given, let me tell you the following:
- The `master` branch README reflects the state of unreleased changes purported to be shipped as v3.0
- GitHub Pages is locked to a particular released version as listed at https://pages.github.com/versions/
- You should navigate to the **tag of the version used** (e.g. [v2.5.1](https://github.com/jekyll/minima/tree/v2.5.1?tab=readme-ov-file#minima)).

If the above does not help resolving your issue, please provide a link to your repository and edit your opening post with what you expected to see but got instead.

**Comment by alexsmacd** [comment]
Hi @ashmaroli. I was using the wrong version; I didn't realize the master branch was unreleased. Once I realized that, all was well. Thank you!

**Comment by alexsmacd** [comment]
Hi @ashmaroli. I was using the wrong version; I didn't realize the master branch was unreleased. Once I realized that, all was well. Thank you!
